services:
  risk-engine-client:
    build: .
    expose:
      - "3000"
    env_file:
      - .env
    restart: always
    container_name: risk-engine-client

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - risk-engine-client
    container_name: caddy

volumes:
  caddy_data:
  caddy_config:
